config/routes.rb
Money::Application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :incomes

  resources :pays

  get "check/state"

  get "manage/index"

end

app/models/income.rb
class Income < ActiveRecord::Base
	validates :date, :goods_type, :name, :price, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0}
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
    @user = User.find(session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @incomes }
    end
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
    @income = Income.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @income }
    end
  end

  # GET /incomes/new
  # GET /incomes/new.json
  def new
    @income = Income.new
    @user = User.find(session[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @income }
    end
  end

  # GET /incomes/1/edit
  def edit
    @income = Income.find(params[:id])
    @user = User.find(session[:user_id])
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(params[:income])

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render json: @income, status: :created, location: @income }
      else
        format.html { render action: "new" }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /incomes/1
  # PUT /incomes/1.json
  def update
    @income = Income.find(params[:id])

    respond_to do |format|
      if @income.update_attributes(params[:income])
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income = Income.find(params[:id])
    @income.destroy

    respond_to do |format|
      format.html { redirect_to incomes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uname, 'User Name: ' %><%= @user.name %><br>
    <%= f.hidden_field :uname, :value => @user.name %>
  </div>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date, :use_month_numbers => true %>
  </div>

  <div class="field">
    <%= f.label :goods_type %><br />
    <%= f.text_field :goods_type %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_area :memo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/incomes/edit.html.erb
<h1>Editing income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<h1>Listing incomes</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Goods type</th>
    <th>Name</th>
    <th>Price</th>
    <th>Memo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @incomes.each do |income| %>
  <% if @user.name == income.uname %>
    <tr>
      <td><%= income.date %></td>
      <td><%= income.goods_type %></td>
      <td><%= income.name %></td>
      <td><%= income.price %></td>
      <td><%= income.memo %></td>
      <td><%= link_to 'Show', income %></td>
      <td><%= link_to 'Edit', edit_income_path(income) %></td>
      <td><%= link_to 'Destroy', income, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Income', new_income_path %>
<%= link_to 'back to top', manage_index_path %>

app/views/incomes/new.html.erb
<h1>New income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @income.date %>
</p>

<p>
  <b>Goods type:</b>
  <%= @income.goods_type %>
</p>

<p>
  <b>Name:</b>
  <%= @income.name %>
</p>

<p>
  <b>Price:</b>
  <%= @income.price %>
</p>

<p>
  <b>Memo:</b>
  <%= @income.memo %>
</p>


<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>