config/routes.rb
Money::Application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :incomes

  resources :pays

  get "check/state"

  get "manage/index"

end

app/models/pay.rb
class Pay < ActiveRecord::Base
	validates :date, :goods_type, :name, :price, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0}
end

app/controllers/pays_controller.rb
class PaysController < ApplicationController
  # GET /pays
  # GET /pays.json
  def index
    @pays = Pay.all
    @nowuser = User.find(session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pays }
    end
  end

  # GET /pays/1
  # GET /pays/1.json
  def show
    @pay = Pay.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pay }
    end
  end

  # GET /pays/new
  # GET /pays/new.json
  def new
    @pay = Pay.new
    @user = User.find(session[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pay }
    end
  end

  # GET /pays/1/edit
  def edit
    @pay = Pay.find(params[:id])
    @user = User.find(session[:user_id])
  end

  # POST /pays
  # POST /pays.json
  def create
    @pay = Pay.new(params[:pay])

#--- save imege file to /public/image/. and assign filename to Pay table ---#
    if params[:image]
      fi = params[:image]
      imagename = fi.original_filename
      File.open("public/image/#{imagename}", 'wb') { |im| im.write(fi.read) }
      @pay.image_url = imagename
    end

#--- save receipt image to /public/receipt/. and assign filename to Pay table---#
    if params[:receipt]
      fr = params[:receipt]
      receiptname = fr.original_filename
      File.open("public/receipt/#{receiptname}", 'wb') { |rm| rm.write(fr.read) }
      @pay.receipt_url = receiptname
    end

    respond_to do |format|
      if @pay.save
        format.html { redirect_to @pay, notice: 'Pay was successfully created.' }
        format.json { render json: @pay, status: :created, location: @pay }
      else
        format.html { render action: "new" }
        format.json { render json: @pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pays/1
  # PUT /pays/1.json
  def update
    @pay = Pay.find(params[:id])

    respond_to do |format|
      if @pay.update_attributes(params[:pay])
        format.html { redirect_to @pay, notice: 'Pay was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pays/1
  # DELETE /pays/1.json
  def destroy
    @pay = Pay.find(params[:id])
    @pay.destroy

    respond_to do |format|
      format.html { redirect_to pays_url }
      format.json { head :ok }
    end
  end
end

app/helpers/pays_helper.rb
module PaysHelper
end

app/views/pays/_form.html.erb
<%= form_for(@pay, :html => {:multipart => true}) do |f| %>
  <% if @pay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pay.errors.count, "error") %> prohibited this pay from being saved:</h2>

      <ul>
      <% @pay.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uname, 'User Name: ' %><%= @user.name %><br>
    <%= f.hidden_field :uname, :value => @user.name %>
  </div>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date, :user_month_numbers => true %>
  </div>
  <div class="field">
    <%= f.label :goods_type %><br />
    <%= f.text_field :goods_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :receipt_url %><br />
    <%= f.text_field :receipt_url %>
  </div>
  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_area :memo %>
  </div>

  <div class="field">
    Image File<br>
    <input name="image" type="file" />
  </div>

  <div class="field">
    Receipt Image<br>
    <input name="receipt" type="file" />
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pays/edit.html.erb
<h1>Editing pay</h1>

<%= render 'form' %>

<%= link_to 'Show', @pay %> |
<%= link_to 'Back', pays_path %>

app/views/pays/index.html.erb
<h1>Listing pays</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Goods type</th>
    <th>Name</th>
    <th>Price</th>
    <th>Image url</th>
    <th>Receipt url</th>
    <th>Memo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pays.each do |pay| %>
  <% if @nowuser.name == pay.uname %>
  <tr>
    <td><%= pay.date %></td>
    <td><%= pay.goods_type %></td>
    <td><%= pay.name %></td>
    <td><%= pay.price %></td>
    <td><%= pay.image_url %></td>
    <td><%= pay.receipt_url %></td>
    <td><%= pay.memo %></td>
    <td><%= link_to 'Show', pay %></td>
    <td><%= link_to 'Edit', edit_pay_path(pay) %></td>
    <td><%= link_to 'Destroy', pay, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Pay', new_pay_path %>
<%= link_to 'back to top', manage_index_path %>

app/views/pays/new.html.erb
<h1>New pay</h1>

<%= render 'form' %>

<%= link_to 'Back', pays_path %>

app/views/pays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @pay.date %>
</p>

<p>
  <b>Goods type:</b>
  <%= @pay.goods_type %>
</p>

<p>
  <b>Name:</b>
  <%= @pay.name %>
</p>

<p>
  <b>Price:</b>
  <%= @pay.price %>
</p>

<p>
  <b>Image</b><br>
  <%= image_tag("../image/#{@pay.image_url}", :size=>"100x100") %>
</p>

<p>
  <b>Receipt image</b><br>
  <%= image_tag("../receipt/#{@pay.receipt_url}", :size=>"100x100") %>
</p>

<p>
  <b>Memo:</b>
  <%= @pay.memo %>
</p>


<%= link_to 'Edit', edit_pay_path(@pay) %> |
<%= link_to 'Back', pays_path %>